# Theoretical Questions

## Q1. What are the different data structures used in Tensorflow? Give some examples

Ans = TensorFlow is a deep learning framework which primarily operates on tensors, which are multi-dimensional arrays.TensorFlow also provides various data structures and abstractions for handling and manipulating data and some of the commonly used data structures are :

1. **Tensors**: Tensors are the fundamental data structure in TensorFlow. They can be of different ranks (0D, 1D, 2D, 3D, etc.) and are similar to multi-dimensional arrays. Tensors can hold numerical data, and they are used for input data, model parameters, and output predictions.

2. **Variables**: TensorFlow Variables are used to hold and update model parameters during training. Unlike constants, variables can be modified and updated during training iterations.

3. **Sparse Tensors**: Sparse tensors are used to represent tensors with a large number of elements that are mostly zero. They are memory-efficient and can speed up certain operations, such as gradient computation in sparse neural networks.

4. **Ragged Tensors**: Ragged tensors are used to represent data with varying lengths, such as sequences of variable-length sentences or lists of different-sized feature vectors.


5. **Tensor Arrays**: Tensor arrays are TensorFlow data structures that allow dynamic and varying-sized tensors to be constructed iteratively. They are often used in dynamic RNNs and custom training loops.


6. **Queues**: TensorFlow provides several queue implementations for managing data input pipelines. These are used in multi-threaded data loading scenarios.

In [1]:
#Implementation of Tensorflow Data Structures
import tensorflow as tf

# Creating tensors
scalar = tf.constant(5)  # 0D tensor (scalar)
vector = tf.constant([1, 2, 3])  # 1D tensor (vector)
matrix = tf.constant([[1, 2], [3, 4]])  # 2D tensor (matrix)

scalar , vector , matrix

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [2]:
# Creating a variable
weights = tf.Variable(tf.random.normal(shape=(3, 3)))
weights

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 1.1978294 ,  0.11992202, -0.4396341 ],
       [ 2.0397694 ,  1.2901398 ,  0.18317275],
       [ 0.88909197, -0.69355637,  1.0056188 ]], dtype=float32)>

In [3]:
# Creating a sparse tensor
indices = tf.constant([[0, 1], [2, 3]],dtype=tf.int64)
values = tf.constant([4.0, 5.0])
shape = tf.constant([3, 4],dtype=tf.int64)
sparse_tensor = tf.sparse.SparseTensor(indices, values, shape)

indices , values , shape , sparse_tensor

(<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[0, 1],
        [2, 3]])>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 5.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int64, numpy=array([3, 4])>,
 SparseTensor(indices=tf.Tensor(
 [[0 1]
  [2 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([4. 5.], shape=(2,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)))

In [4]:
# Creating a ragged tensor
ragged_tensor = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])
ragged_tensor

<tf.RaggedTensor [[1, 2], [3, 4, 5], [6]]>

In [5]:
# Creating a tensor array
tensor_array = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
tensor_array

In [6]:
# Creating a FIFO queue
queue = tf.queue.FIFOQueue(capacity=10, dtypes=tf.float32)
queue

## Q2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example

Ans = 1. **TensorFlow Constants**:

   - Constants are used to represent fixed values in TensorFlow.
   - Once you create a constant, its value cannot be changed. It remains constant throughout the execution of the program.
   - Constants are typically used for values that should not be modified during training, such as hyperparameters or fixed input data.
   - They are stored in memory, but their values do not get updated during training.

   

2. **TensorFlow Variables**:

   - Variables are used to represent modifiable tensors in TensorFlow.
   - Variables are commonly used to store and update model parameters (weights and biases) during training.
   - Unlike constants, the values of variables can be changed using operations like `assign` or by training them using optimization algorithms.
   - Variables are usually initialized with initial values, and their values evolve during training.

The key difference between TensorFlow constants and variables is that constants have fixed values that do not change during execution, while variables are mutable and can change their values over time, making them suitable for representing model parameters during training.

In [7]:
#Example of a TensorFlow constant

import tensorflow as tf

# Creating a TensorFlow constant
constant_tensor = tf.constant([1, 2, 3])

try:
  constant_tensor.assign([4, 5, 6])
  print("Try Block is Executed !!")

except Exception as e:
  print("Error !! Attempting to change the value of a constant")

Error !! Attempting to change the value of a constant


In [8]:
#Example of a TensorFlow Varibale

import tensorflow as tf

# Creating a TensorFlow variable
initial_values = tf.constant([1, 2, 3])
variable_tensor = tf.Variable(initial_values)

try:

  # Modifying the value of a variable
  new_values = tf.constant([4, 5, 6])
  variable_tensor.assign(new_values)
  print("Try Block is Executed !!")
  # Print the updated variable
  print(variable_tensor.numpy())

except Exception as e:
  print("Except Block is Executed !!")

Try Block is Executed !!
[4 5 6]


## Q3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

Ans = These are fundamental operations in TensorFlow for working with matrices and tensors:

1. **Matrix Addition**:

   Matrix addition in TensorFlow is performed using the tf.add or simply the + operator. It adds corresponding elements of two tensors of the same shape. The tensors being added must have compatible shapes (same number of rows and columns).

2. **Matrix Multiplication**:

   Matrix multiplication in TensorFlow is performed using the tf.matmul function. This operation computes the dot product of two matrices. The inner dimensions of the matrices must match for matrix multiplication to be valid.

3. **Element-Wise Operations**:

   Element-wise operations in TensorFlow involve applying an operation to each element of a tensor independently. Common element-wise operations include addition, subtraction, multiplication, division, and more. These operations can be performed using standard Python operators or TensorFlow functions like tf.add, tf.subtract, tf.multiply, and tf.divide.

In [9]:
import tensorflow as tf

# Create two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition using add function
result_matrix = tf.add(matrix1, matrix2)
# Perform matrix addition using + operator
result_matrixx = matrix1 + matrix2

# Print the result
print(f"Matrix 1 : \n\n{matrix1.numpy()}")
print(f"\nMatrix 2 : \n\n{matrix2.numpy()}")
print(f"\nAddition Using add function : \n\n{result_matrix.numpy()}")
print(f"\nAddition Using + operator : \n\n{result_matrix.numpy()}")

Matrix 1 : 

[[1 2]
 [3 4]]

Matrix 2 : 

[[5 6]
 [7 8]]

Addition Using add function : 

[[ 6  8]
 [10 12]]

Addition Using + operator : 

[[ 6  8]
 [10 12]]


In [10]:
import tensorflow as tf

# Create two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result_matrix = tf.matmul(matrix1, matrix2)

# Print the result
print(f"Matrix 1 : \n\n{matrix1.numpy()}")
print(f"\nMatrix 2 : \n\n{matrix2.numpy()}")
print(f"\nAddition Using add function : \n\n{result_matrix.numpy()}")

Matrix 1 : 

[[1 2]
 [3 4]]

Matrix 2 : 

[[5 6]
 [7 8]]

Addition Using add function : 

[[19 22]
 [43 50]]


In [11]:
import tensorflow as tf

# Create two tensors
tensor1 = tf.constant([[1, 2],[3,4]])
scaler = 2

# Perform element-wise addition
result_add = tf.add(tensor1,scaler)

# Perform element-wise multiplication
result_multiply = tf.multiply(tensor1, scaler)

# Perform element-wise division
result_div = tf.divide(tensor1, scaler)

# Perform element-wise subraction
result_subract = tf.subtract(tensor1, scaler)


# Perform element-wise square
result_square = tf.square(tensor1)


# Print the result
print(f"Tensor 1 : \n\n{tensor1.numpy()}")
print(f"\nScaler : \n\n{scaler}")
print(f"\nElement Wise Addition with scaler : \n\n{result_add.numpy()}")
print(f"\nElement Wise Subraction with scaler : \n\n{result_subract.numpy()}")
print(f"\nElement Wise Multiplication with scaler : \n\n{result_multiply.numpy()}")
print(f"\nElement Wise Division with scaler : \n\n{result_div.numpy()}")
print(f"\nElement Wise Square : \n\n{result_square.numpy()}")

Tensor 1 : 

[[1 2]
 [3 4]]

Scaler : 

2

Element Wise Addition with scaler : 

[[3 4]
 [5 6]]

Element Wise Subraction with scaler : 

[[-1  0]
 [ 1  2]]

Element Wise Multiplication with scaler : 

[[2 4]
 [6 8]]

Element Wise Division with scaler : 

[[0.5 1. ]
 [1.5 2. ]]

Element Wise Square : 

[[ 1  4]
 [ 9 16]]


# Practical Implementation

## Q4.  Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A

In [12]:
import tensorflow as tf

print("TensorFlow version: {}".format(tf.__version__))

TensorFlow version: 2.17.1


In [13]:
A = tf.random.normal([3,3],dtype = tf.float32,seed=42)
print(f"Matrix A : \n\n{A.numpy()}")

Matrix A : 

[[-0.28077507 -0.1377521  -0.6763296 ]
 [ 0.02458041 -0.89358455 -0.82847327]
 [ 1.2068944   1.3810157  -1.4557977 ]]


## 5. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B

In [14]:
B = tf.random.truncated_normal(shape=[4,4], dtype=tf.float32,seed=42)
print(f"Matrix B : \n\n{B.numpy()}")

Matrix B : 

[[-0.28077507 -0.1377521  -0.6763296   0.02458041]
 [-0.46845472 -0.00246632 -0.9745911   0.6638492 ]
 [ 0.4368011  -0.7038976   0.6426843   1.4513893 ]
 [ 1.8412819  -0.15879929 -1.0607921   1.5984018 ]]


## Q6. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C

In [15]:
C = tf.random.normal([2,2],mean=3, stddev=0.5,dtype = tf.float32,seed=42)
print(f"Matrix C : \n\n{C.numpy()}")

Matrix C : 

[[3.609005  2.8007267]
 [3.3198366 2.6839418]]


## Q7. Perform matrix addition between matrix A and matrix B, and store the result in matrix D

In [16]:
#It is impossible to add A and B as A is 3X3 Matrix and B is 4X4 matrix
#For Matrix Addition the shape of the Matrix should be Similiar
#So reshaping A and B
A = tf.random.normal([2,3],dtype = tf.float32,seed=42)
B = tf.random.truncated_normal([2,3],dtype = tf.float32,seed=42)

D = A+B
print(f"Matrix A : \n\n{A.numpy()}")
print(f"\nMatrix B : \n\n{B.numpy()}")
print(f"\nMatrix D : \n\n{D.numpy()}")

Matrix A : 

[[ 1.4171269   0.806262   -0.6378367 ]
 [-0.59586287  0.9795361   0.86680996]]

Matrix B : 

[[-0.18655936  0.21760897  0.1489197 ]
 [ 0.07509567  0.5019556   1.0746589 ]]

Matrix D : 

[[ 1.2305676  1.023871  -0.488917 ]
 [-0.5207672  1.4814918  1.9414688]]


## Q8. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [17]:
E = tf.matmul(C,D)
print(f"Matrix C : \n\n{C.numpy()}")
print(f"\nMatrix D : \n\n{D.numpy()}")
print(f"\nMatrix E : \n\n{E.numpy()}")

Matrix C : 

[[3.609005  2.8007267]
 [3.3198366 2.6839418]]

Matrix D : 

[[ 1.2305676  1.023871  -0.488917 ]
 [-0.5207672  1.4814918  1.9414688]]

Matrix E : 

[[2.9825978 7.844409  3.6730194]
 [2.6875744 7.3753223 3.5876646]]


# Performing Additional Matrix Operations

## Q9. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function

In [18]:
F = tf.random.uniform([3,3],dtype = tf.float32,seed=42)
print(f"Matrix F : \n\n{F.numpy()}")

Matrix F : 

[[0.95227146 0.67740774 0.79531825]
 [0.75578177 0.4759556  0.6310148 ]
 [0.18602037 0.11430776 0.3362218 ]]


## Q10. Calculate the transpose of matrix F and store the result in matrix G

In [19]:
G = tf.transpose(F)
print(f"Matrix F : \n\n{F.numpy()}")
print(f"\nMatrix G : \n\n{G.numpy()}")

Matrix F : 

[[0.95227146 0.67740774 0.79531825]
 [0.75578177 0.4759556  0.6310148 ]
 [0.18602037 0.11430776 0.3362218 ]]

Matrix G : 

[[0.95227146 0.75578177 0.18602037]
 [0.67740774 0.4759556  0.11430776]
 [0.79531825 0.6310148  0.3362218 ]]


## Q11. Calculate the element-wise exponential of matrix F and store the result in matrix H

In [20]:
H = tf.exp(F)
print(f"Matrix F : \n\n{F.numpy()}")
print(f"\nMatrix H : \n\n{H.numpy()}")

Matrix F : 

[[0.95227146 0.67740774 0.79531825]
 [0.75578177 0.4759556  0.6310148 ]
 [0.18602037 0.11430776 0.3362218 ]]

Matrix H : 

[[2.5915897 1.9687675 2.2151458]
 [2.1292756 1.6095515 1.879517 ]
 [1.2044468 1.1210971 1.3996495]]


## Q12. Create a matrix I by concatenating matrix F and matrix G horizontally

In [21]:
I= tf.concat([F,G],axis=0)
print(f"Matrix F : \n\n{F.numpy()}")
print(f"\nMatrix G : \n\n{G.numpy()}")
print(f"\nMatrix I : \n\n{I.numpy()}")

Matrix F : 

[[0.95227146 0.67740774 0.79531825]
 [0.75578177 0.4759556  0.6310148 ]
 [0.18602037 0.11430776 0.3362218 ]]

Matrix G : 

[[0.95227146 0.75578177 0.18602037]
 [0.67740774 0.4759556  0.11430776]
 [0.79531825 0.6310148  0.3362218 ]]

Matrix I : 

[[0.95227146 0.67740774 0.79531825]
 [0.75578177 0.4759556  0.6310148 ]
 [0.18602037 0.11430776 0.3362218 ]
 [0.95227146 0.75578177 0.18602037]
 [0.67740774 0.4759556  0.11430776]
 [0.79531825 0.6310148  0.3362218 ]]


## Q13. Create a matrix J by concatenating matrix F and matrix H vertically.

In [22]:
J= tf.concat([F,H],axis=1)
print(f"Matrix F : \n\n{F.numpy()}")
print(f"\nMatrix H : \n\n{H.numpy()}")
print(f"\nMatrix J : \n\n{J.numpy()}")

Matrix F : 

[[0.95227146 0.67740774 0.79531825]
 [0.75578177 0.4759556  0.6310148 ]
 [0.18602037 0.11430776 0.3362218 ]]

Matrix H : 

[[2.5915897 1.9687675 2.2151458]
 [2.1292756 1.6095515 1.879517 ]
 [1.2044468 1.1210971 1.3996495]]

Matrix J : 

[[0.95227146 0.67740774 0.79531825 2.5915897  1.9687675  2.2151458 ]
 [0.75578177 0.4759556  0.6310148  2.1292756  1.6095515  1.879517  ]
 [0.18602037 0.11430776 0.3362218  1.2044468  1.1210971  1.3996495 ]]
